### ISSUE TITLE
Crystal asymmetry?

### ISSUE THREAD

**Issue by evitts** [GRIFFINCollaboration/detectorSimulations_v10#22]
Could someone do me a favour and run the following short macro to compare results...

```
/DetSys/phys/SelectPhysics emlivermore
/run/initialize
/process/em/fluo true
/process/em/auger true
/process/em/pixe true

/DetSys/det/SetCustomShieldsPresent 0
/DetSys/det/SetCustomRadialDistance 11 cm
/DetSys/det/SetCustomExtensionSuppressorLocation 0
/DetSys/det/includeGriffinHevimet 0

/DetSys/det/SetCustomDeadLayer 1 1 0
/DetSys/det/addGriffinCustomDetector 1
/DetSys/det/SetCustomDeadLayer 2 2 0
/DetSys/det/addGriffinCustomDetector 2
/DetSys/det/SetCustomDeadLayer 3 3 0
/DetSys/det/addGriffinCustomDetector 3
/DetSys/det/SetCustomDeadLayer 4 4 0
/DetSys/det/addGriffinCustomDetector 4
/DetSys/det/SetCustomDeadLayer 5 5 0
/DetSys/det/addGriffinCustomDetector 5
/DetSys/det/SetCustomDeadLayer 6 6 0
/DetSys/det/addGriffinCustomDetector 6
/DetSys/det/SetCustomDeadLayer 7 7 0
/DetSys/det/addGriffinCustomDetector 7
/DetSys/det/SetCustomDeadLayer 8 8 0
/DetSys/det/addGriffinCustomDetector 8
/DetSys/det/SetCustomDeadLayer 9 9 0
/DetSys/det/addGriffinCustomDetector 9
/DetSys/det/SetCustomDeadLayer 10 10 0
/DetSys/det/addGriffinCustomDetector 10
/DetSys/det/SetCustomDeadLayer 11 11 0
/DetSys/det/addGriffinCustomDetector 11
/DetSys/det/SetCustomDeadLayer 12 12 0
/DetSys/det/addGriffinCustomDetector 12
/DetSys/det/SetCustomDeadLayer 13 13 0
/DetSys/det/addGriffinCustomDetector 13
/DetSys/det/SetCustomDeadLayer 14 14 0
/DetSys/det/addGriffinCustomDetector 14
/DetSys/det/SetCustomDeadLayer 15 15 0
/DetSys/det/addGriffinCustomDetector 15
/DetSys/det/SetCustomDeadLayer 16 16 0
/DetSys/det/addGriffinCustomDetector 16

/DetSys/app/addGriffinStructure 0

/gun/particle gamma
/gun/energy 500 keV
/run/beamOn 1000000
```

After running it I see an asymmetry of counts in the crystals:
![image](https://cloud.githubusercontent.com/assets/6774176/19908131/244c860a-a03f-11e6-874e-13c4bfaffb2e.png)
I'm no GRIFFIN expert but I assume the crystals are the same size...  I could be wrong in the commands also?  The deposited energy is not what I would have expected either:

![image](https://cloud.githubusercontent.com/assets/6774176/19908203/70e6e19a-a03f-11e6-9c0e-faffc74083ba.png)

Only 1,400 counts detected when 1,000,000 emitted

**Comment by AndrewMac1** [comment]
First thing I will ask is how long did the simulation take to run? If it ran in a few seconds then the problem is most likely that there wasn't a direction set for your gamma's. With no direction set I think default is in the z-direction and the only events you will see are scatters off of the default atmosphere. This would also cause an asymmetry in the crystal output as the crystals near the z-axis would more likely see these scatters. Just make sure you set a direction for your gamma's using /gun/direction. Really I think we should have it that we are using general particle source (gps) rather than the gun. @jturko I know you've done this but have you committed this yet to the code?

Just as a double check I ran it anyways and if you use verbose to see some output such as:
/control/verbose 1
/run/verbose 0
/event/verbose 0
/tracking/verbose 1  <---This provided the output below

you'll see you get a ton of the following:
*********************************************************************************************************
* G4Track Information:   Particle = gamma,   Track ID = 1,   Parent ID = 0
*********************************************************************************************************

Step#    X(mm)    Y(mm)    Z(mm) KinE(MeV)  dE(MeV) StepLeng TrackLeng  NextVolume ProcName
    0        0                0             0           0.5              0              0               0              World initStep
    1        0                0         5e+03       0.5              0           5e+03      5e+03      OutOfWorld Transportation

*********************************************************************************************************
These are exactly what I described above.

**Comment by AndrewMac1** [comment]
Unfortunately the verbose doesn't like to copy and paste well apparently but if you dare to try to follow the zeroes it says there was one step where it left the world volume in the z-direction.

**Comment by evitts** [comment]
D'oh, I assumed there'd be a default distribution.
Cheers!

**Comment by evitts** [comment]
So it does, by default, emit in a uniform distribution if you set the particle energy with the confusing name

    /DetSys/gun/efficiencyEnergy

rather than 
 
    /gun/energy 500 keV

which I got from one of the macro files.
