### ISSUE TITLE
Problems setting up Sceptar detectors

### ISSUE THREAD

**Issue by smayotte** [GRIFFINCollaboration/detectorSimulations_v10#86]
When trying to set up the sceptar detectors the way it is shown (albeit commented) in some of the example run files with
`/DetSys/det/addSceptar 20`
I get the following message when running the simulation:
```
Unknown detector number 10 for square SCEPTAR!
Unknown detector number 10 for angled SCEPTAR!
```
In addition, if I look at the visualization only one sceptar detector shows up.
I used the same command (`/DetSys/det/addSceptar 20`) in a much older version of the detector simulation and there it worked very nicely and all the detectors show up in visualization.
Any ideas as to what I could be doing wrong?

**Comment by VinzenzBildstein** [comment]
I just tried this by modifying the run.mac macro in `example_simulations/descant_simulation_example` and it worked fine for me as far as the visualization goes:
![Screenshot from 2023-09-12 16-38-11](https://github.com/GRIFFINCollaboration/detectorSimulations_v10/assets/7277216/34b83edb-6a17-4b16-ac5e-5c69e742097b)
I did get the same error messages, and they seem to be because the volume names start counting at `1` instead of `0`. I've changed that in `DetectorConstruction.cc` and pushed the changes (see #87).

**Comment by smayotte** [comment]
Yup, it works now. Thanks a bunch!
